from dataclasses import dataclass
from typing import List, Tuple, Optional, Any
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

# Project constants (assumed present in your project)
import core.constants
from core.my_data_types import PlotSetup

ma_group_names = list(core.constants.ma_groups.keys())  # short, medium, long

# ---------------------------
# Plotting
# ---------------------------
def plot_index_vs_ma_vwma(df_to_plot: pd.DataFrame, ps: PlotSetup) -> plt.Figure:
    """
    Plot index price and MA/VWMA overlays. Expects df_to_plot to contain columns generated by calculate_ma_vwma_max_min.
    Returns a matplotlib Figure.
    """
    df_to_plot = df_to_plot.tail(ps.lookback_period)
    fig, axs = plt.subplots(2, 1, figsize=(18, 9), sharex=True)

    #--------------------
    # TOP subplot - SMAs
    # --------------------
    ax = axs[0]
    ax_twin = ax.twinx()

    ax.set_title(f"{ps.mkt} price vs MAs (with MA max/min ranges). {ps.sample_start}-{ps.sample_end}",
                 fontsize=12, fontweight="bold")

    # Use Plot_setup to plot Adj Close between max/min and shaded and grids)
    ps.plot_price_layer(ax)

    for ma in core.constants.mas_list:
        col = f"MA{ma}"
        col_label = f"{ma}-day mov. avg"
        if col in df_to_plot.columns:
            ax.plot(ps.plot_index, df_to_plot[col], color=core.constants.ma_color_map.get(col, None), label=col_label, zorder=5)

    # bar ranges
    if 'MA_range' in df_to_plot.columns:
        ax.bar(ps.plot_index, df_to_plot['MA_range'], bottom=ps.ymin, width=1.0, label='Max/min MA range', alpha=0.8)
    if 'MA_no200_range' in df_to_plot.columns:
        ax.bar(ps.plot_index, df_to_plot['MA_no200_range'], bottom=ps.ymin, width=1.0, label='Max/min MA range (no 200day MA)', alpha=0.5)

    ax.tick_params(axis='y', labelsize=8)
    ax.grid(True, axis='both')
    #ax_twin.bar(ps.plot_index, df_to_plot['Volume'], width=1.0, alpha=0.3, label='Volume')
    # Invert volume bars to draw downward
    vol = df_to_plot['Volume'].astype(float)
    ax_twin.bar(ps.plot_index, -vol, width=1.0, alpha=0.3, label='Volume (inverted)')
    ax_twin.set_ylim(-vol.max(), 0)  # show negative values (bars extend down)
    ax_twin.set_yticks([])  # hide ticks
    #ax_twin.set_ylabel('')  # hide label to unclutter

    ax_twin.set_ylabel('Volume', fontsize=9)

    lines, labels = ax.get_legend_handles_labels()
    lines2, labels2 = ax_twin.get_legend_handles_labels()
    ax_twin.legend(lines + lines2, labels + labels2, loc='upper left', fontsize=8, frameon=True)

    #----------------------
    # LOWER subplot - VWMAs
    # ---------------------
    ax = axs[1]
    ax_twin = ax.twinx()

    ax.set_title(f"{ps.mkt} price vs VWMAs, with VWMA (max-min) ranges and range-oscillator", fontsize=12, fontweight="bold")

    # Use Plot_setup to plot Adj Close between max/min and shaded and grids)
    ps.plot_price_layer(ax)

    for ma in core.constants.mas_list:
        col = f"VWMA{ma}"
        col_label = f"{ma}-day vol. weighted MA"
        if col in df_to_plot.columns:
            ax.plot(ps.plot_index, df_to_plot[col], color=core.constants.ma_color_map.get(col, None), label=col, zorder=5)

    if 'VWMA_range' in df_to_plot.columns:
        ax.bar(ps.plot_index, df_to_plot['VWMA_range'], bottom=ps.ymin, width=1.0, label='Max/min VWMA range', alpha=0.9)
    if 'VWMA_no200_range' in df_to_plot.columns:
        ax.bar(ps.plot_index, df_to_plot['VWMA_no200_range'], bottom=ps.ymin, width=1.0, label='Max/min VWMA range (no 200 day VWMA)', alpha=0.7)

    if 'VWMA_no200_osc_scaled' in df_to_plot.columns:
        ax.bar(ps.plot_index, df_to_plot['VWMA_no200_osc_scaled'], color='green', width=1.0, label='VWMA range osc. (scaled 0-1)', alpha=0.5)
        scale = 0.2 * (ps.ymax - ps.ymin) + ps.ymin
        ax.axhline(y=scale, color='green', linestyle='--', linewidth=2.0, alpha=0.9)

    ax.tick_params(axis='y', labelsize=8)
    #ax_twin.bar(ps.plot_index, df_to_plot['Volume'], width=1.0, alpha=0.3, label='Volume')
    # Invert volume bars to draw downward
    vol = df_to_plot['Volume'].astype(float)
    ax_twin.bar(ps.plot_index, -vol, width=1.0, alpha=0.3, label='Volume (inverted)')
    ax_twin.set_ylim(-vol.max(), 0)  # show negative values (bars extend down)
    ax_twin.set_yticks([])  # hide ticks
    #ax_twin.set_ylabel('')  # hide label to unclutter

    ax_twin.set_ylabel('Volume', fontsize=9)

    # x-axis formatting: use bottom subplot axis
    ps.fix_xlimits(ax)
    ps.apply_xaxis(ax)

    lines, labels = ax.get_legend_handles_labels()
    lines2, labels2 = ax_twin.get_legend_handles_labels()
    ax_twin.legend(lines + lines2, labels + labels2, loc='upper left', fontsize=8, frameon=True)

    return fig


def plot_tickers_over_under_mas(df_to_plot: pd.DataFrame, ps: PlotSetup) -> plt.Figure:
    """
    Plot percent of tickers above/below groupings of MAs/VWMAs.
    """
    df_to_plot = df_to_plot.tail(ps.lookback_period)

    ma_group_names = list(core.constants.ma_groups.keys())  # short, medium, long
    fig, axs = plt.subplots(3, 1, figsize=(18, 9), sharex=True)

    for pc, ax in enumerate(axs):
        ma_grouping = ma_group_names[pc]
        ax_twin = ax.twinx()
        title_start = f"{ps.mkt}: {ps.sample_start}-{ps.sample_end}" if pc == 0 else ""
        ax.set_title(f"{title_start} - Net % (tickers over minus tickers under) {ma_grouping} volume weighted moving avgs", fontsize=12, fontweight="bold")

        # Use Plot_setup to plot Adj Close between max/min and shaded and grids)
        ps.plot_price_layer(ax)

        for ma in core.constants.ma_groups[ma_grouping]["periods"]:
            col = f"%±VWMA{ma}"
            col_label = f"Net over/under {ma}-day VWMA"
            if col in df_to_plot.columns:
                ax_twin.plot(ps.plot_index, df_to_plot[col], color=core.constants.ma_color_map.get(col, None), label=col_label)
                ax_twin.axhline(y=0, color='black', linestyle='--')
                ax_twin.fill_between(ps.plot_index, df_to_plot[col], 0, where=(df_to_plot[col] >= 0), alpha=0.5, interpolate=True)
                ax_twin.fill_between(ps.plot_index, df_to_plot[col], 0, where=(df_to_plot[col] <= 0), alpha=0.5, interpolate=True)

        ax_twin.set_ylabel(f'% of {ps.num_tickers} tickers', fontsize=9)
        ax_twin.legend(loc='upper left')

        ax.grid(True, axis='x')
        ax_twin.grid(True, axis='y')
        ps.fix_xlimits(ax)
        ps.apply_xaxis(ax)

        lines, labels = ax.get_legend_handles_labels()
        lines2, labels2 = ax_twin.get_legend_handles_labels()
        ax_twin.legend(lines + lines2, labels + labels2, loc='upper left', fontsize=8, frameon=True)

    return fig


def plot_absolute_compression_bands(idx_ma_df: pd.DataFrame,
                                    comp_ma_df: pd.DataFrame,
                                    ps: PlotSetup) -> plt.Figure:
    """
    Plot absolute VWMA compression as:
    - band (upper/lower)
    - percent-bandwidth normalized indicator

    idx_ma_df : index-level price
    comp_ma_df : per-ticker VWMA compression (MultiIndex)
    """
    idx_ma_df = idx_ma_df.tail(ps.lookback_period)
    comp_ma_df = comp_ma_df.tail(ps.lookback_period)

    fig, ax = plt.subplots(3, 1,
                           figsize=(18, 9),
                           gridspec_kw={"height_ratios": [5, 3, 2]},
                           sharex=True)

    # -----------------------------------------------------------------
    # FIRST PLOT: PRICE + BANDS
    # -----------------------------------------------------------------
    ax_price = ax[0]
    ax_band  = ax_price.twinx()
    ax_band.grid(True, axis="y", linestyle="--", alpha=0.5)
    # zero line
    ax_band.axhline(y=0, color="blue", linewidth=2.4, alpha=0.85)

    ax_price.set_title(
        f"{ps.mkt}: {ps.sample_start}-{ps.sample_end} — VWMA Compression Bands",
        fontsize=13, fontweight="bold"
    )
    ps.plot_price_layer(ax_price)
    #ps.apply_xaxis(ax_price)

    # Storage for bandwidth calculations
    band_upper = {}
    band_lower = {}
    pct_bandwidth = {}

    # -----------------------------------------------------------------
    # COMPUTE BANDS
    for group_name, group_info in core.constants.ma_groups.items():
        periods = group_info["periods"]
        color   = group_info["color"]

        group_frames = []

        for ma in periods:
            key = f"C-VWMA{ma}"
            if key in comp_ma_df.columns.get_level_values(0):
                df_sub = comp_ma_df[key]        # (dates × tickers)
                group_frames.append(df_sub)

        if not group_frames:
            continue

        group_df = pd.concat(group_frames, axis=1)

        upper = group_df.max(axis=1)
        lower = group_df.min(axis=1)

        band_upper[group_name] = upper
        band_lower[group_name] = lower

        ax_band.fill_between(
            ps.plot_index,
            lower,
            upper,
            alpha=0.30,
            color=color,
            label=f"{group_name} band"
        )

    ax_band.set_ylabel("Absolute Compression Range")
    ax_band.legend(loc="upper left", fontsize=9)

    # -----------------------------------------------------------------
    # SECOND PLOT: PERCENT BANDWIDTH (0–1)
    # -----------------------------------------------------------------
    ax_price = ax[1]
    ax_bw = ax_price.twinx()

    ps.plot_price_layer(ax_price)
    #ps.apply_xaxis(ax_price)

    # -----------------------------------------------------------------
    # COMPUTE BANDWIDTH
    for group_name, group_info in core.constants.ma_groups.items():
        if group_name not in band_upper:
            continue

        upper = band_upper[group_name]
        lower = band_lower[group_name]

        raw_width = upper - lower
        max_width = raw_width.max()

        pct_bw = raw_width / (max_width + 1e-9)
        pct_bandwidth[group_name] = pct_bw

        ax_bw.plot(ps.plot_index,
                   pct_bw,
                   color=group_info["color"],
                   lw=1.8,
                   label=f"{group_name} bandwidth")

    ax_bw.set_title("Percent Bandwidth (Normalized Compression)", fontsize=12)
    ax_bw.set_ylim(0, 1)
    ax_bw.grid(True)
    ax_bw.legend(loc="upper left")

    # ==================================================================
    #   THIRD PLOT: HEATMAP OF ALL VWMA DISPERSION WIDTHS
    # ==================================================================

    ax_hm = ax[2]
    plot_dates = idx_ma_df.index
    x = ps.plot_index

    vwma_periods = sorted([
        ma
        for g in core.constants.ma_groups.values()
        for ma in g["periods"]
    ])

    rows = []
    labels = []

    for ma in vwma_periods:
        key = f"C-VWMA{ma}"
        if key not in comp_ma_df.columns.get_level_values(0):
            continue

        sub = comp_ma_df[key]
        width = (sub.max(axis=1) - sub.min(axis=1)).reindex(plot_dates).ffill()

        # normalize 0..1 per row
        w_norm = (width - width.min()) / (width.max() - width.min() + 1e-9)
        rows.append(w_norm.values)
        labels.append(f"VWMA{ma}")

    if rows:
        heat = np.array(rows)
        im = ax_hm.imshow(
            heat,
            cmap="hot",
            aspect="auto",
            interpolation="nearest",
            extent=[0, len(x), 0, len(rows)]
        )

        ax_hm.set_title("VWMA Dispersion Heatmap")
        ax_hm.set_yticks(np.arange(len(labels)) + 0.5)
        ax_hm.set_yticklabels(labels, fontsize=9)

        ps.apply_xaxis(ax_hm)

        #fig.colorbar(im, ax=ax_hm, fraction=0.018, pad=0.02)

    return fig
